### ISSUE TITLE
Fabric API version wrongly collects fstats-api version

### ISSUE THREAD

**Issue by MightyKnight** [fStats/fstats-api#3]
The Fabric API chart shows the version `2023.12.2` for most players, however `2023.12.2` is and has _never_ been a version of Fabric Api.
It is however a version of **fstats-api** according to my latest.log.
```
- bluemapofflineplayermarkers 2.9.1-fabric
    |-- com_github_technicjelle_bmutils v1.1
    \-- fstats-api 2023.12.2
```

Example on this project: https://fstats.dev/project/43  

![grafik](https://github.com/fStats/fstats-api/assets/38622942/1e9a3a81-9344-4eab-b440-1f058ebbf1a4)

**Comment by syorito-hatsuki** [comment]
Old issue that already fixed in fStats Lib, but I didn't have time to update BluemapOfflinePlayerMarkers because it need rewrite anyway to simplify migration from original Paper plugin to Fabric Port

**Comment by syorito-hatsuki** [comment]
(I fixed it, but didn't updated on github😅)

**Comment by syorito-hatsuki** [comment]
https://modrinth.com/mod/fstats/version/2023.12.3

**Comment by MightyKnight** [comment]
Thank you. I was actually considering that BluemapOfflinePlayerMarkers might use an older version, but only looked on Github.

Props to you for maintaining the Fabric port of BluemapOfflinePlayerMarkers, very useful and it just works in exactly the situations we need it. No need to hurry to rewrite it, I think the rewrite is behind the scenes just for you. Because honestly there's nothing missing.

P.S. I was really confused by the lone `0.96.4+1.20.4` in that chart, now that I know more, I'm pretty sure that's you with your dev environment. 😄
