### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by hotsu0p** [fStats/fstats-api#4]
When i added it no data appears in the website

**Comment by syorito-hatsuki** [comment]
What and how did you do. Please write full process so I can say faster what wrong

**Comment by syorito-hatsuki** [comment]
So, you author of architect. I decompiled your mod. First of all you didn't added custom param for fStats to `fabric.mod.json`
![image](https://github.com/fStats/fstats-api/assets/33298273/c4303ece-eb6a-462d-8281-f2a964ac5e8d)
![image](https://github.com/fStats/fstats-api/assets/33298273/cdd44cbf-132a-416d-b347-8d832044184b)

Second, currently mod send only information from server usage, but client side support is already on roadmap for that year.

**Comment by hotsu0p** [comment]
huh alr i thought i added that. thanks tho
